-- Add vision-analysis result column to product_assets
ALTER TABLE `product_assets` ADD `analysis` text;
--> statement-breakpoint

-- Add visual-detail columns to image_items (generated by design-plan LLM)
ALTER TABLE `image_items` ADD `lighting` text;
--> statement-breakpoint
ALTER TABLE `image_items` ADD `angle` text;
--> statement-breakpoint
ALTER TABLE `image_items` ADD `background` text;
--> statement-breakpoint
ALTER TABLE `image_items` ADD `mood` text;
--> statement-breakpoint
ALTER TABLE `image_items` ADD `visual_elements` text;
--> statement-breakpoint

-- Which product photo to use as reference image for this image item
ALTER TABLE `image_items` ADD `product_asset_id` text;
--> statement-breakpoint

-- Also add missing columns to api_request_logs that schema defines but 0001 missed
ALTER TABLE `api_request_logs` ADD `query_string` text;
--> statement-breakpoint
ALTER TABLE `api_request_logs` ADD `request_body` text;
--> statement-breakpoint
ALTER TABLE `api_request_logs` ADD `response_body` text;
